<?php
use Core\Lang;
?>


        <h1><?=Lang::translate('User registration')?></h1>


        <?php if ($validation_errors && !empty($validation_errors)){ ?>

            You have made some validation errors while completing this form
            Please check and fix them: <br>

            <?php foreach ($validation_errors as $error) { ?>

                <b> <?=$error?> </b> </br>

             <?php }
        }  ?>



        <div class="col-md-8 order-md-1">
          <h1 class="mb-3"></h1>
          <form action="<?php echo $this->basePath; ?>user/add" method="POST" enctype="multipart/form-data">

              <div class="mb-3">
              <label for="username">Username</label>
              <div class="input-group">
                <input tooltipText="Type in your username in this box. At least 6 symbols" type="text" class="form-control" id="username" name="username" placeholder="Username" required>
                <div class="invalid-feedback" style="width: 100%;"></div>
              </div>
            </div>

            <div class="mb-3">
              <label for="email">Email <span class="text-muted"></span></label>
              <input type="email" tooltipText="Type your valid email" class="form-control" id="email" name="email" placeholder="you@example.com" required>
              <div class="invalid-feedback"></div>
            </div>
              
              
             <div class="mb-3">
              <label for="password">Password <span class="text-muted"></span></label>
              <input type="password" tooltipText="Create access password. Password should contain both letter and numbers. At least 6 symbols"  class="form-control" id="password" name="password"  required>
              <div class="invalid-feedback"></div>
             </div>

              <div class="mb-3">
                  <label for="firstname">First name</label>
                  <div class="input-group">
                      <input type="text" tooltipText="Type in your first name in this box. At least 3 symbols"class="form-control" id="firstname" name="firstname" placeholder="first name" required>
                      <div class="invalid-feedback" style="width: 100%;"></div>
                  </div>
              </div>


              <div class="mb-3">
                  <label for="lastname">Last name</label>
                  <div class="input-group">
                      <input type="text" tooltipText="Type in your last name in this box. At least 3 symbols" class="form-control" id="lastname" name="lastname" placeholder="last name" required>
                      <div class="invalid-feedback" style="width: 100%;"></div>
                  </div>
              </div>
              
              

            <div class="mb-3">
              <label for="description">About me</label>
              <textarea tooltipText="Write about youself" class="form-control" id="description" name="description" required></textarea>
              <div class="invalid-feedback"></div>
            </div>

            <div class="mb-3">
              <label for="image">Profile image</label>
              <input type="file" tooltipText="Choose your profile image" class="form-control" id="image" name="image">
            </div>

            <button class="btn btn-primary" type="submit" name="submit_add_user" value="Submit" >Sign up!</button>
          </form>
        </div>

<script type="text/javascript">
    var tooltipObj = new DHTMLgoodies_formTooltip();
    tooltipObj.setTooltipPosition('right');
    tooltipObj.setPageBgColor('#EEEEEE');
    tooltipObj.setTooltipCornerSize(15);
    tooltipObj.initFormFieldTooltip();
</script>





