<?php
use Core\Lang;
?>


        <h1><?=Lang::translate('User registration')?></h1>


        <?php if ($validation_errors && !empty($validation_errors)){ ?>


            <?=Lang::translate('validation_text')?>:

            <br>

            <?php foreach ($validation_errors as $error) { ?>

                <b> <?=$error?> </b> </br>

             <?php }
        }  ?>



        <div class="col-md-8 order-md-1">
          <h1 class="mb-3"></h1>
          <form action="<?php echo $this->basePath; ?>user/add" method="POST" enctype="multipart/form-data">

              <div class="mb-3">
              <label for="username"><?=Lang::translate('Username')?></label>
              <div class="input-group">
                <input tooltipText="<?=Lang::translate('Type in your username in this box. At least 6 symbol')?>s" type="text" class="form-control" id="username" name="username" placeholder="<?=Lang::translate('Username')?>" required>
                <div class="invalid-feedback" style="width: 100%;"></div>
              </div>
            </div>

            <div class="mb-3">
              <label for="email"><?=Lang::translate('Email')?> <span class="text-muted"></span></label>
              <input type="email" tooltipText="<?=Lang::translate('Type your valid email')?>" class="form-control" id="email" name="email" placeholder="you@example.com" required>
              <div class="invalid-feedback"></div>
            </div>
              
              
             <div class="mb-3">
              <label for="password"><?=Lang::translate('Password')?> <span class="text-muted"></span></label>
              <input type="password" tooltipText="<?=Lang::translate('Create access password. Password should contain both letter and numbers. At least 6 symbols')?>"  class="form-control" id="password" name="password"  required>
              <div class="invalid-feedback"></div>
             </div>

              <div class="mb-3">
                  <label for="firstname"><?=Lang::translate('First name')?></label>
                  <div class="input-group">
                      <input type="text" tooltipText="<?=Lang::translate('Type in your first name in this box. At least 3 symbols')?>"class="form-control" id="firstname" name="firstname" placeholder="<?=Lang::translate('First name')?>" required>
                      <div class="invalid-feedback" style="width: 100%;"></div>
                  </div>
              </div>


              <div class="mb-3">
                  <label for="lastname"><?=Lang::translate('Last name')?></label>
                  <div class="input-group">
                      <input type="text" tooltipText="<?=Lang::translate('Type in your last name in this box. At least 3 symbols')?>"class="form-control" id="lastname" name="lastname" placeholder="<?=Lang::translate('Last name')?>" required>
                      <div class="invalid-feedback" style="width: 100%;"></div>
                  </div>
              </div>
              
              

            <div class="mb-3">
              <label for="description"><?=Lang::translate('About me')?></label>
              <textarea tooltipText="<?=Lang::translate('Write about youself')?>" class="form-control" id="description" name="description" required></textarea>
              <div class="invalid-feedback"></div>
            </div>

            <div class="mb-3">
              <label for="image"><?=Lang::translate('Profile image')?></label>
              <input type="file" tooltipText="<?=Lang::translate('Choose your profile image')?>" required class="form-control" id="image" name="image">
            </div>

            <button class="btn btn-primary" type="submit" name="submit_add_user" value="Submit" ><?=Lang::translate('Sign up')?>!</button>
          </form>
        </div>

<script type="text/javascript">
    var tooltipObj = new DHTMLgoodies_formTooltip();
    tooltipObj.setTooltipPosition('right');
    tooltipObj.setPageBgColor('#EEEEEE');
    tooltipObj.setTooltipCornerSize(15);
    tooltipObj.initFormFieldTooltip();
</script>

<script>
    CKEDITOR.replace( 'description' );
</script>





